[package]
name = "carboxyl-toggle"
version = "0.1.0"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[dependencies]
carboxyl = "0.2"
carboxyl_window = "0.0.3"
benzene = "0.1"
benzene-2d = "0.1"
elmesque = "0.12"
glium = "0.13"
piston = "0.17"
